In [1]:
#numpy = numerical phyton

In [5]:
tinggi = [51,72,64,87,90]
lebar = [100,201,51,12,10]

#cari area

tinggi * lebar #tidak bisa list*list

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
import numpy as np

In [6]:
arr_tinggi = np.array(tinggi)
arr_lebar = np.array(lebar)
#panjang = ([10,20,30,40,50])
arr_panjang = np.array([10,20,30,40,50])

hasil = arr_tinggi * arr_lebar * arr_panjang
print(hasil, type(hasil))

[ 51000 289440  97920  41760  45000] <class 'numpy.ndarray'>


In [7]:
# simpan posisi papan catur di dalam array -> 2D
[
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
]

[[1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8]]

In [8]:
# built-in function milik numpy, contohnya:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.empty(4)

array([ 2.68156159e+154, -2.32035459e+077,  1.73059952e-077,
        2.78134232e-309])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
for i in range(7,15,2):
    print(i)

7
9
11
13


In [15]:
arr_numbers = np.arange(7,15,2)
arr_numbers

array([ 7,  9, 11, 13])

In [16]:
arr_numbers = np.append(arr_numbers, 15)
arr_numbers

array([ 7,  9, 11, 13, 15])

In [17]:
hasil = np.append(arr_numbers, [15,17])
print(hasil)
print(type(hasil))

[ 7  9 11 13 15 15 17]
<class 'numpy.ndarray'>


In [18]:
tempel2list = np.append([1,2,3],[4,5,6])
print(type(tempel2list))

<class 'numpy.ndarray'>


In [19]:
np.delete(tempel2list, 1)

array([1, 3, 4, 5, 6])

In [20]:
hasil_return = np.delete(tempel2list, 1)
print(hasil_return)

[1 3 4 5 6]


In [21]:
random_nums = np.array([-1,1,-5,5,-30,30]) #array yang random atau tidak urut
np.sort(random_nums) #jadi urut

array([-30,  -5,  -1,   1,   5,  30])

In [22]:
random_nums #tetap tidak berurutan karena tidak disort

array([ -1,   1,  -5,   5, -30,  30])

In [23]:
random_nums.ndim

1

In [24]:
arr_2d = np.array([
    ["o","x","o"," "],
    ["o","x","o"," "],
    ["o","x","o"," "],
])

In [25]:
arr_2d.ndim

2

In [26]:
arr_2d.size

12

In [27]:
random_nums.size

6

In [28]:
arr_2d.shape

(3, 4)

In [29]:
random_nums.shape

(6,)

In [30]:
transposed = arr_2d.reshape(4,3)
transposed

array([['o', 'x', 'o'],
       [' ', 'o', 'x'],
       ['o', ' ', 'o'],
       ['x', 'o', ' ']], dtype='<U1')

In [31]:
transposed.shape

(4, 3)

In [32]:
arr_nums_baru = random_nums [np.newaxis]
arr_nums_baru

array([[ -1,   1,  -5,   5, -30,  30]])

In [33]:
random_nums[np.newaxis, :]

array([[ -1,   1,  -5,   5, -30,  30]])

In [34]:
random_nums[:, np.newaxis]

array([[ -1],
       [  1],
       [ -5],
       [  5],
       [-30],
       [ 30]])

In [35]:
np.expand_dims(random_nums, axis=0)

array([[ -1,   1,  -5,   5, -30,  30]])

In [36]:
np.expand_dims(random_nums, axis=1)

array([[ -1],
       [  1],
       [ -5],
       [  5],
       [-30],
       [ 30]])

In [37]:
random_nums[-3:]

array([  5, -30,  30])

In [38]:
random_nums[1:5]

array([  1,  -5,   5, -30])

In [39]:
#cara indexing dan slicing di numpy array sama persis dengan di list

In [44]:
random_nums[random_nums < 0]

array([ -1,  -5, -30])

In [45]:
random_nums [random_nums %2 == 0]

array([-30,  30])

In [46]:
random_nums [random_nums %2 == 1]

array([-1,  1, -5,  5])

In [47]:
random_nums [(random_nums < 0) & (random_nums %2 == 1)]

array([-1, -5])

In [48]:
arr_a = np.array([[1,2], [3,4]])
arr_a

array([[1, 2],
       [3, 4]])

In [49]:
arr_b = np.array ([[5,6], [7,8]])
arr_b

array([[5, 6],
       [7, 8]])

In [50]:
np.vstack((arr_a, arr_b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
np.hstack((arr_a, arr_b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
np.vstack((arr_b, arr_a))

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [53]:
h_arr = np.hstack((arr_a, arr_b))
h_arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
hasil = np.hsplit(h_arr, 4) #hasil list yang isinya numpy array
print(hasil)
print(type(hasil))

[array([[1],
       [3]]), array([[2],
       [4]]), array([[5],
       [7]]), array([[6],
       [8]])]
<class 'list'>


In [55]:
np.hsplit(np.zeros(12), 4)

[array([0., 0., 0.]),
 array([0., 0., 0.]),
 array([0., 0., 0.]),
 array([0., 0., 0.])]

In [56]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
b = a.view()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
np.append(b, [20,30])
print(b)

[100   1   2   3   4   5   6   7   8   9  10  11]


In [59]:
b[0] = 100
print(b)
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [60]:
c = a.copy()
c[0]=9
print(c)
print(a)

[ 9  1  2  3  4  5  6  7  8  9 10 11]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [71]:
h_arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [64]:
h_arr.sum(axis=0)

array([ 4,  6, 12, 14])

In [65]:
h_arr.sum(axis=1)

array([14, 22])

In [75]:
h_arr + np.ones(8).reshape(2,4)

array([[2., 3., 6., 7.],
       [4., 5., 8., 9.]])

In [76]:
h_arr - np.ones(8).reshape(2,4)

array([[0., 1., 4., 5.],
       [2., 3., 6., 7.]])

In [77]:
h_arr * np.ones(8).reshape(2,4) + np.ones(8).reshape(2,4)

array([[2., 3., 6., 7.],
       [4., 5., 8., 9.]])

In [78]:
h_arr / np.ones(8).reshape(2,4) + np.ones(8).reshape(2,4)

array([[2., 3., 6., 7.],
       [4., 5., 8., 9.]])

In [79]:
h_arr *2

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [80]:
h_arr/2

array([[0.5, 1. , 2.5, 3. ],
       [1.5, 2. , 3.5, 4. ]])

In [81]:
h_arr +2

array([[ 3,  4,  7,  8],
       [ 5,  6,  9, 10]])

In [83]:
data_awal = h_arr +3
data_awal

array([[ 4,  5,  8,  9],
       [ 6,  7, 10, 11]])

In [84]:
# min max sum mean std

data_awal.min()

4

In [85]:
data_awal.max()

11

In [86]:
data_awal.sum()

60

In [87]:
data_awal.mean()

7.5

In [88]:
data_awal.std()

2.29128784747792

In [89]:
#Matrix

[
    [1,2],
    [3,4]
    
]

[[1, 2], [3, 4]]

In [101]:
m1 = np.array([
    [1,2,3],
    [4,5,6]
])

m2= np.array([
    [7,8],
    [9,10],
    [11,12]
])

hasil = np.dot(m1, m2) #melakukan dot product antar 2 matrix
hasil

array([[ 58,  64],
       [139, 154]])

In [102]:
hasil[0,0]

58

In [103]:
hasil[1]

array([139, 154])

In [104]:
hasil[1,1]

154

In [105]:
hasil[:,1]

array([ 64, 154])

In [106]:
m2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [109]:
m2.reshape(2,3)

array([[ 7,  8,  9],
       [10, 11, 12]])

In [110]:
m2.T #row 1 jadi kolom 1, row 2 jadi kolom 2, dst

array([[ 7,  9, 11],
       [ 8, 10, 12]])

In [111]:
np.zeros(3)

array([0., 0., 0.])

In [119]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [118]:
np.zeros((5,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [120]:
np.random.random(2)

array([0.13524336, 0.81932516])

In [122]:
np.random.random(5)

array([0.79373166, 0.65984268, 0.40310608, 0.10835709, 0.32362122])

In [125]:
arr_3d = np.zeros((5,2,3))

In [126]:
arr_3d.flatten() #menjadi satu dimensi

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
arr_3d.ravel() #sama seperti flatten tapi shallow copy, seperti view

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])